### ISSUE TITLE
!aj <username> not addressing properly

### ISSUE THREAD

**Issue by minus273dot15** [dripton/blahblahblahbot#6]
When running `!aj <username>` I'm seeing the bot to address the requester, and not the addressee, e.g.:
```
15:16:24 <user1> !aj user2
15:16:24 <bot> user1, Nice!
```
My logic is that it should've printed:
```
15:16:24 <user1> !aj user2
15:16:24 <bot> user2, Nice!
```

**Comment by dripton** [comment]
Fixed in d1b3e9a0e61d00a9b7ecde6e3d2907ad66af9681
